apiVersion: apps/v1
kind: Deployment
metadata:
  name: nestjs-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nestjs-app
  template:
    metadata:
      labels:
        app: nestjs-app
    spec:
      containers:
      - name: nestjs-app
        image: kaiserautomata/census-bolumbia-backend-app:11
        ports:
        - containerPort: 3000
        env:
        - name: DATABASE_HOST
          value: 'postgres-service'
        - name: DATABASE_PORT
          value: '5432'
        - name: DATABASE_USER
          value: 'root'
        - name: DATABASE_PASSWORD
          value: 'root'
        - name: DATABASE_NAME
          value: 'postgresql'
